services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data:
